### ISSUE TITLE
I don't know why it's especially slow to initialize in wsl2

### ISSUE THREAD

**Issue by horanf** [glepnir/cosynvim#30]
It takes about ten seconds, during which I can't do anything

**Comment by glepnir** [comment]
use `nvim --startuptime time.log` to see what happen

**Comment by horanf** [comment]
thanks for the quick reply。
![image](https://user-images.githubusercontent.com/92006580/200800721-2fa76b98-11d9-48cb-af78-8b30473cba42.png)

**Comment by horanf** [comment]
I am using archliux in wsl2, just now i installed lolcat, but it's still slow。Maybe there is something wrong with my description, i can't edit it after start it not initialize , during which it can't work for more than ten seconds.

**Comment by glepnir** [comment]
`slow` that mean your startup time too big or something else?  you can use ascii text dashboard without lolcat. more usage you can find in dashboard readme.

**Comment by notwidow** [comment]
> thanks for the quick reply。 ![image](https://user-images.githubusercontent.com/92006580/200800721-2fa76b98-11d9-48cb-af78-8b30473cba42.png)

Install lolcat or edit the config file of dashboard and remove or modify the header options. Also you may need to install other programs like gcc compiler for tree-sitter in arch. since arch is a minimal distribution with its aim "do it yourself". so you need to do everything yourself.
 Remove all "db.preview" options from modules/ui/config.lua.
